block.settings.single_file_component_block:wri_search_menu:
  type: block_settings
  label: 'WRIN Search block'
  mapping:
    search_nav_title:
      type: text
      label: 'Search box title'
    search_nav_description:
      type: text
      label: 'Search box description'
    search_nav_label:
      type: text
      label: 'Input label'
    search_nav_destination:
      type: text
      label: 'Form destination url'
    search_nav_id:
      type: string
      label: 'Block ID'
    search_nav_submit:
      type: text
      label: 'Submit button text'

# Schema for the configuration files of the WRIN Search module.
wri_search.settings:
  type: config_object
  label: 'WRIN Search settings'
  mapping:
    enable_google:
      type: boolean
      label: 'Use Google Custom Search'
